// Command gen-protocol emits the TypeScript protocol definitions shared with
// the desktop app from the canonical Go enums (internal/db, internal/recording).
// Run via `make gen-protocol`; verify with `make check-protocol`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/gappd-dev/gappd/internal/db"
	"github.com/gappd-dev/gappd/internal/recording"
)

const header = `// Code generated by ` + "`go run ./cmd/gen-protocol`" + `. DO NOT EDIT.
// Source of truth: internal/db (statuses, meeting states) and internal/recording (event names).
`

func main() {
	check := flag.Bool("check", false, "verify the generated file is up to date instead of writing it")
	out := flag.String("out", "desktop/src/shared/generated/protocol.ts", "output path")
	flag.Parse()

	content := render()
	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil || string(existing) != content {
			fmt.Fprintf(os.Stderr, "%s is out of date; run `make gen-protocol`\n", *out)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func render() string {
	var b strings.Builder
	b.WriteString(header)
	writeEnum(&b, "CAPTURE_STATUSES", "CaptureStatus", values(db.AllCaptureStatuses))
	writeEnum(&b, "PROCESSING_STATUSES", "ProcessingStatus", values(db.AllProcessingStatuses))
	writeEnum(&b, "MEETING_STATES", "MeetingState", values(db.AllMeetingStates))
	writeEnum(&b, "RECORDING_PROTOCOL_EVENT_TYPES", "RecordingProtocolEventType", values(recording.AllEventNames))
	return b.String()
}

func writeEnum(b *strings.Builder, constName, typeName string, vals []string) {
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = "'" + v + "'"
	}
	fmt.Fprintf(b, "\nexport const %s = [%s] as const\n", constName, strings.Join(quoted, ", "))
	fmt.Fprintf(b, "export type %s = (typeof %s)[number]\n", typeName, constName)
}

func values[T ~string](in []T) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}
