// Command gen-protocol emits TypeScript protocol definitions shared with
// the desktop app from canonical Go protocol specs.
// Run via `make gen-protocol`; verify with `make check-protocol`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/gappd-dev/gappd/internal/db"
	"github.com/gappd-dev/gappd/internal/meetinglifecycle"
	"github.com/gappd-dev/gappd/internal/meetingprocessing"
	"github.com/gappd-dev/gappd/internal/recording"
)

const protocolHeader = `// Code generated by ` + "`go run ./cmd/gen-protocol`" + `. DO NOT EDIT.
// Source of truth: internal/db, internal/meetinglifecycle, internal/recording, internal/appprotocol.
`

func main() {
	check := flag.Bool("check", false, "verify generated files are up to date")
	protocolOut := flag.String("out", "desktop/src/shared/generated/protocol.ts", "enum output path")
	contractsOut := flag.String("contracts-out", "desktop/src/shared/generated/contracts.ts", "contract output path")
	appOut := flag.String("app-out", "desktop/src/shared/generated/app-protocol.ts", "app protocol output path")
	lifecycleOut := flag.String("lifecycle-out", "desktop/src/shared/generated/lifecycle.ts", "lifecycle helper output path")
	flag.Parse()

	files := map[string]string{*protocolOut: renderProtocol(), *contractsOut: renderContracts(), *appOut: renderAppProtocol(), *lifecycleOut: renderLifecycle(), liveActionContractsPath(*contractsOut): renderLiveActionContracts()}
	if *check {
		checkFiles(files)
		return
	}
	writeFiles(files)
}

func checkFiles(files map[string]string) {
	for path, content := range files {
		existing, err := os.ReadFile(path)
		if err != nil || string(existing) != content {
			fmt.Fprintf(os.Stderr, "%s is out of date; run `make gen-protocol`\n", path)
			os.Exit(1)
		}
	}
}

func writeFiles(files map[string]string) {
	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fail(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fail(err)
		}
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func renderProtocol() string {
	var b strings.Builder
	b.WriteString(protocolHeader)
	writeEnum(&b, "CAPTURE_STATUSES", "CaptureStatus", values(db.AllCaptureStatuses))
	writeEnum(&b, "PROCESSING_STATUSES", "ProcessingStatus", values(db.AllProcessingStatuses))
	writeEnum(&b, "DIARIZATION_STATES", "DiarizationState", values(db.AllDiarizationStates))
	writeEnum(&b, "PROCESSING_CAPABILITIES", "ProcessingCapability", values(meetingprocessing.AllCapabilities))
	writeEnum(&b, "MEETING_STATES", "MeetingState", values(meetinglifecycle.AllMeetingStates))
	writeEnum(&b, "RECORDING_PROTOCOL_EVENT_TYPES", "RecordingProtocolEventType", values(recording.AllEventNames))
	return b.String()
}

func writeEnum(b *strings.Builder, constName, typeName string, vals []string) {
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = quote(v)
	}
	fmt.Fprintf(b, "\nexport const %s = [%s] as const\n", constName, strings.Join(quoted, ", "))
	fmt.Fprintf(b, "export type %s = (typeof %s)[number]\n", typeName, constName)
}

func renderLifecycle() string {
	var b strings.Builder
	b.WriteString(protocolHeader)
	b.WriteString("\nimport type { MeetingState } from './protocol'\n")
	writeStatusToneType(&b)
	writeStatusToneFunction(&b)
	writeStatusPillFunction(&b)
	return b.String()
}

func writeStatusToneType(b *strings.Builder) {
	fmt.Fprintf(b, "\nexport type MeetingStatusTone = %s\n", union(values(meetinglifecycle.AllMeetingStatusTones)))
}

func writeStatusToneFunction(b *strings.Builder) {
	b.WriteString("\nexport function meetingStatusTone(state: MeetingState): MeetingStatusTone {\n  switch (state) {\n")
	for _, state := range meetinglifecycle.AllMeetingStates {
		fmt.Fprintf(b, "    case %s: return %s\n", quote(string(state)), quote(string(meetinglifecycle.MeetingStatusToneFor(state))))
	}
	b.WriteString("  }\n}\n")
}

func writeStatusPillFunction(b *strings.Builder) {
	b.WriteString("\nexport function meetingStatusPillVisible(state: MeetingState): boolean {\n  return meetingStatusTone(state) !== 'idle'\n}\n")
}
