// Command gen-protocol emits TypeScript protocol definitions shared with
// the desktop app from canonical Go protocol specs.
// Run via `make gen-protocol`; verify with `make check-protocol`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/gappd-dev/gappd/internal/appprotocol"
	"github.com/gappd-dev/gappd/internal/db"
	"github.com/gappd-dev/gappd/internal/meetinglifecycle"
	"github.com/gappd-dev/gappd/internal/meetingprocessing"
	"github.com/gappd-dev/gappd/internal/recording"
)

const protocolHeader = `// Code generated by ` + "`go run ./cmd/gen-protocol`" + `. DO NOT EDIT.
// Source of truth: internal/db, internal/meetinglifecycle, internal/recording, internal/appprotocol.
`

type typeCollector struct {
	seen  map[reflect.Type]bool
	order []reflect.Type
}

func main() {
	check := flag.Bool("check", false, "verify generated files are up to date")
	protocolOut := flag.String("out", "desktop/src/shared/generated/protocol.ts", "enum output path")
	contractsOut := flag.String("contracts-out", "desktop/src/shared/generated/contracts.ts", "contract output path")
	appOut := flag.String("app-out", "desktop/src/shared/generated/app-protocol.ts", "app protocol output path")
	lifecycleOut := flag.String("lifecycle-out", "desktop/src/shared/generated/lifecycle.ts", "lifecycle helper output path")
	flag.Parse()

	files := map[string]string{*protocolOut: renderProtocol(), *contractsOut: renderContracts(), *appOut: renderAppProtocol(), *lifecycleOut: renderLifecycle()}
	if *check {
		checkFiles(files)
		return
	}
	writeFiles(files)
}

func checkFiles(files map[string]string) {
	for path, content := range files {
		existing, err := os.ReadFile(path)
		if err != nil || string(existing) != content {
			fmt.Fprintf(os.Stderr, "%s is out of date; run `make gen-protocol`\n", path)
			os.Exit(1)
		}
	}
}

func writeFiles(files map[string]string) {
	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fail(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fail(err)
		}
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func renderProtocol() string {
	var b strings.Builder
	b.WriteString(protocolHeader)
	writeEnum(&b, "CAPTURE_STATUSES", "CaptureStatus", values(db.AllCaptureStatuses))
	writeEnum(&b, "PROCESSING_STATUSES", "ProcessingStatus", values(db.AllProcessingStatuses))
	writeEnum(&b, "PROCESSING_CAPABILITIES", "ProcessingCapability", values(meetingprocessing.AllCapabilities))
	writeEnum(&b, "MEETING_STATES", "MeetingState", values(meetinglifecycle.AllMeetingStates))
	writeEnum(&b, "RECORDING_PROTOCOL_EVENT_TYPES", "RecordingProtocolEventType", values(recording.AllEventNames))
	return b.String()
}

func writeEnum(b *strings.Builder, constName, typeName string, vals []string) {
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = quote(v)
	}
	fmt.Fprintf(b, "\nexport const %s = [%s] as const\n", constName, strings.Join(quoted, ", "))
	fmt.Fprintf(b, "export type %s = (typeof %s)[number]\n", typeName, constName)
}

func renderContracts() string {
	collector := collectCommandTypes()
	var b strings.Builder
	b.WriteString(protocolHeader)
	b.WriteString("\nimport type { CaptureStatus, MeetingState, ProcessingCapability, ProcessingStatus, RecordingProtocolEventType } from './protocol'\n")
	for _, typ := range collector.order {
		writeType(&b, typ)
	}
	return b.String()
}

func renderLifecycle() string {
	var b strings.Builder
	b.WriteString(protocolHeader)
	b.WriteString("\nimport type { MeetingState } from './protocol'\n")
	writeStatusToneType(&b)
	writeStatusToneFunction(&b)
	writeStatusPillFunction(&b)
	return b.String()
}

func writeStatusToneType(b *strings.Builder) {
	fmt.Fprintf(b, "\nexport type MeetingStatusTone = %s\n", union(values(meetinglifecycle.AllMeetingStatusTones)))
}

func writeStatusToneFunction(b *strings.Builder) {
	b.WriteString("\nexport function meetingStatusTone(state: MeetingState): MeetingStatusTone {\n  switch (state) {\n")
	for _, state := range meetinglifecycle.AllMeetingStates {
		fmt.Fprintf(b, "    case %s: return %s\n", quote(string(state)), quote(string(meetinglifecycle.MeetingStatusToneFor(state))))
	}
	b.WriteString("  }\n}\n")
}

func writeStatusPillFunction(b *strings.Builder) {
	b.WriteString("\nexport function meetingStatusPillVisible(state: MeetingState): boolean {\n  return meetingStatusTone(state) !== 'idle'\n}\n")
}

func collectCommandTypes() typeCollector {
	collector := typeCollector{seen: map[reflect.Type]bool{}}
	for _, command := range appprotocol.Commands {
		collector.add(command.Input)
		collector.add(command.Output)
		collector.add(command.Event)
	}
	return collector
}

func (c *typeCollector) add(typ reflect.Type) {
	if typ == nil {
		return
	}
	typ = deref(typ)
	if !isStructFromAppProtocol(typ) || c.seen[typ] {
		return
	}
	c.seen[typ] = true
	c.order = append(c.order, typ)
	for i := 0; i < typ.NumField(); i++ {
		c.add(typ.Field(i).Type)
	}
}

func isStructFromAppProtocol(typ reflect.Type) bool {
	return typ.Kind() == reflect.Struct && typ.PkgPath() == "github.com/gappd-dev/gappd/internal/appprotocol"
}

func writeType(b *strings.Builder, typ reflect.Type) {
	if typ.NumField() == 0 {
		fmt.Fprintf(b, "\nexport type %s = Record<string, never>\n", typ.Name())
		return
	}
	fmt.Fprintf(b, "\nexport type %s = {\n", typ.Name())
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if !field.IsExported() {
			continue
		}
		name, optional := jsonName(field)
		fmt.Fprintf(b, "  %s%s: %s\n", name, optionalMark(optional), tsType(field.Type))
	}
	b.WriteString("}\n")
}

func jsonName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	parts := strings.Split(tag, ",")
	if parts[0] == "" {
		parts[0] = field.Name
	}
	return parts[0], contains(parts[1:], "omitempty") || field.Type.Kind() == reflect.Pointer
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func tsType(typ reflect.Type) string {
	if typ.Kind() == reflect.Pointer {
		return tsType(typ.Elem())
	}
	if enumName := enumTypeName(typ); enumName != "" {
		return enumName
	}
	return baseTSType(typ)
}

func baseTSType(typ reflect.Type) string {
	switch typ.Kind() {
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Bool:
		return "boolean"
	case reflect.Slice, reflect.Array:
		return tsType(typ.Elem()) + "[]"
	case reflect.Struct:
		return typ.Name()
	default:
		return "unknown"
	}
}

func enumTypeName(typ reflect.Type) string {
	switch typ {
	case reflect.TypeOf(db.CaptureStatus("")):
		return "CaptureStatus"
	case reflect.TypeOf(db.ProcessingStatus("")):
		return "ProcessingStatus"
	case reflect.TypeOf(meetinglifecycle.MeetingState("")):
		return "MeetingState"
	case reflect.TypeOf(meetingprocessing.Capability("")):
		return "ProcessingCapability"
	case reflect.TypeOf(recording.EventName("")):
		return "RecordingProtocolEventType"
	default:
		return ""
	}
}

func renderAppProtocol() string {
	var b strings.Builder
	b.WriteString(protocolHeader)
	b.WriteString(appProtocolImports())
	writeMapType(&b, "AppCommandInput", inputTypeName)
	writeMapType(&b, "AppCommandOutput", outputTypeName)
	writeCommandHelpers(&b)
	writeCommandMap(&b)
	writeCommandTypes(&b)
	return b.String()
}

func appProtocolImports() string {
	types := appProtocolTypeNames()
	return fmt.Sprintf("\nimport type { %s } from './contracts'\nimport type { RecordingProtocolEventType } from './protocol'\n", strings.Join(types, ", "))
}

func appProtocolTypeNames() []string {
	seen := map[string]bool{}
	for _, command := range appprotocol.Commands {
		addTypeName(seen, inputTypeName(command))
		addTypeName(seen, outputTypeName(command))
		addTypeName(seen, eventTypeName(command))
	}
	return sortedKeys(seen)
}

func addTypeName(seen map[string]bool, name string) {
	if name != "" {
		seen[name] = true
	}
}

func writeCommandHelpers(b *strings.Builder) {
	b.WriteString(`
type CommandDefinition<Input> = {
  mode: 'request' | 'stream'
  args(input: Input): string[]
  env: readonly string[]
  terminal: readonly RecordingProtocolEventType[]
}

type AppCommandDefinitions = { [K in keyof AppCommandInput]: CommandDefinition<AppCommandInput[K]> }
`)
}

func writeCommandMap(b *strings.Builder) {
	b.WriteString("\nexport const APP_COMMANDS = {\n")
	for _, command := range appprotocol.Commands {
		fmt.Fprintf(b, "  %s: { mode: %s, args: (input: %s) => %s, env: %s, terminal: %s },\n", quote(command.ID), quote(string(command.Mode)), inputTypeName(command), argsExpr(command.Args), stringList(command.Env), eventList(command.Terminal))
	}
	b.WriteString("} as const satisfies AppCommandDefinitions\n")
}

func writeCommandTypes(b *strings.Builder) {
	b.WriteString("\nexport type AppCommandID = keyof typeof APP_COMMANDS\n")
	b.WriteString("export type AppRequestID = keyof AppCommandOutput\n")
	b.WriteString("export type AppStreamID = { [K in AppCommandID]: AppCommandMode<K> extends 'stream' ? K : never }[AppCommandID]\n")
	b.WriteString("export type AppCommandMode<ID extends AppCommandID> = (typeof APP_COMMANDS)[ID]['mode']\n")
	writeStreamEventType(b)
}

func writeStreamEventType(b *strings.Builder) {
	b.WriteString("export type AppStreamEvent<ID extends AppStreamID> = {\n")
	for _, command := range appprotocol.StreamCommands() {
		fmt.Fprintf(b, "  %s: %s\n", quote(command.ID), eventTypeName(command))
	}
	b.WriteString("}[ID]\n")
}

func writeMapType(b *strings.Builder, name string, value func(appprotocol.CommandSpec) string) {
	b.WriteString("\nexport type " + name + " = {\n")
	for _, command := range appprotocol.Commands {
		if typeName := value(command); typeName != "" {
			fmt.Fprintf(b, "  %s: %s\n", quote(command.ID), typeName)
		}
	}
	b.WriteString("}\n")
}

func argsExpr(args []appprotocol.CommandArg) string {
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		parts = append(parts, argExpr(arg))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func argExpr(arg appprotocol.CommandArg) string {
	if arg.Literal != "" {
		return quote(arg.Literal)
	}
	if arg.Flag == "" {
		return fieldExpr(arg)
	}
	if arg.Optional {
		return optionalFlagExpr(arg)
	}
	return quote("--"+arg.Flag) + ", " + fieldExpr(arg)
}

func optionalFlagExpr(arg appprotocol.CommandArg) string {
	return fmt.Sprintf("...(input.%s === undefined ? [] : [%s, %s])", arg.Field, quote("--"+arg.Flag), fieldExpr(arg))
}

func fieldExpr(arg appprotocol.CommandArg) string {
	expr := "input." + arg.Field
	if arg.Stringify {
		return "String(" + expr + ")"
	}
	return expr
}

func inputTypeName(command appprotocol.CommandSpec) string {
	return command.Input.Name()
}

func outputTypeName(command appprotocol.CommandSpec) string {
	if command.Output == nil {
		return ""
	}
	return command.Output.Name()
}

func eventTypeName(command appprotocol.CommandSpec) string {
	if command.Event == nil {
		return ""
	}
	return command.Event.Name()
}

func sortedKeys(in map[string]bool) []string {
	out := make([]string, 0, len(in))
	for key := range in {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func contains(items []string, target string) bool {
	for _, item := range items {
		if item == target {
			return true
		}
	}
	return false
}

func deref(typ reflect.Type) reflect.Type {
	for typ.Kind() == reflect.Pointer || typ.Kind() == reflect.Slice || typ.Kind() == reflect.Array {
		typ = typ.Elem()
	}
	return typ
}

func stringList(items []string) string {
	quoted := make([]string, len(items))
	for i, item := range items {
		quoted[i] = quote(item)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func eventList(items []recording.EventName) string {
	return stringList(values(items))
}

func union(items []string) string {
	quoted := make([]string, len(items))
	for i, item := range items {
		quoted[i] = quote(item)
	}
	return strings.Join(quoted, " | ")
}

func quote(value string) string {
	return "'" + value + "'"
}

func values[T ~string](in []T) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}
